export const ADD_INPUTFIELD_DETAILS = "ADD_INPUTFIELD_DETAILS";
export const ADD_FILTEREDARRAY = "ADD_FILTEREDARRAY";
// export const UPDATE_INPUTFIELD_DETAILS = "UPDATE_INPUTFIELD_DETAILS";
// export const REMOVE_INPUTFIELD_DETAILS = "REMOVE_INPUTFIELD_DETAILS";
